### ISSUE TITLE
alibaba-ubuntu aarch64 machines fail to fetch jdk17 debug builds from upstream

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1976]
**The Problem**
This:
```
00:31:36  Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] dir
00:31:36  Running in /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_linux/openjdkbinary
[Pipeline] {
[Pipeline] copyArtifacts
01:31:36  Cancelling nested steps due to timeout
```
Where "copyArtifacts" is us attempting to copy some upstream packages, including a debug image, and likely a normal build and a package of test native files too.

Also, these failures have this at the end of the job, after we leave the node:
```
Timeout has been exceeded
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:218)
	at hudson.remoting.PipeWindow$Real.get(PipeWindow.java:232)
	at hudson.remoting.ProxyOutputStream.write(ProxyOutputStream.java:126)
Caused: java.io.InterruptedIOException
	at hudson.remoting.ProxyOutputStream.write(ProxyOutputStream.java:151)
	at hudson.remoting.RemoteOutputStream.write(RemoteOutputStream.java:111)
	at java.security.DigestOutputStream.write(DigestOutputStream.java:145)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1159)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:878)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1135)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:854)
	at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:709)
Caused: java.io.IOException: Failed to copy file:/home/jenkins/.jenkins/jobs/build-scripts/jobs/jobs/jobs/jdk/jobs/jdk-linux-aarch64-openj9/builds/252/archive/workspace/target/OpenJDK-debugimage_aarch64_linux_openj9_2021-02-23-23-30.tar.gz to /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_linux/openjdkbinary/OpenJDK-debugimage_aarch64_linux_openj9_2021-02-23-23-30.tar.gz
	at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:731)
	at hudson.plugins.copyartifact.CopyArtifact.copy(CopyArtifact.java:674)
	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:634)
	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:518)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$541/000000000000000000.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
Finished: ABORTED
```

Note: Appears to happen consistently on alibaba-ubuntu machines, but has only been seen on jdk17 j9 builds thus far.

**Machines Affected**

build-alibaba-ubuntu1804-armv8-1
test-alibaba-ubuntu1804-armv8-1

**Examples**

https://trss.adoptopenjdk.net/output/build?id=6035f9425730424dbc8f5d04
https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux_xl/5/console

**Grinder to Reproduce**
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=extended.openjdk&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&PLATFORM=aarch64_linux_xl&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=test-alibaba-ubuntu1804-armv8-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=17&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk%2Fjdk-linux-aarch64-openj9-linuxXL&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=&OPENJDK_SHA=&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=68&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None

Note: The issue is a 1hr hang. The copyArtifacts process, on other machines, usually takes 2-2.5 mins, so if it's still trying to "copyArtifacts" after 5 mins you can probably call it a hang.

**Todo**
- [x] Run a small grinder to see if this still happens on the affected machines.
- [ ] Run a bigger grinder to see if this happens 100% of the time.
- [ ] Run a grinder to ensure this doesn't happen on the other aarch64 machines.
- [ ] Run a jdk16 grinder to verify that this only happens on jdk17. Ditto for hs and j9 (as we've only seen the issue on the latter).
- [ ] Get access to the machine in question.
- [ ] Dig into the source for copyArtifacts and develop a minimal test case.

**Comment by adamfarley** [comment]
Still working on this.

**Comment by sxa** [comment]
> Still working on this.

Are you still doing so? You're not assigned to it at the moment.

**Comment by adamfarley** [comment]
I moved this onto the backburner. Back on it now.

I'm not assigned to it because I don't seem to have that authority to assign myself. Could you assign me to it?

**Comment by adamfarley** [comment]
Grinder running to see if this still happens.

https://ci.adoptopenjdk.net/job/Grinder/7313/console

**Comment by sxa** [comment]
Not sure what's gone on here - it looks like the machine has been rebuilt from scratch so jenkins cannot connect into it - I'll contact Alibaba

**Comment by sxa** [comment]
I've re-run the playbook on it. Unclear why it got into that state but hopefully you can now retry the test on the machine and see if it's still a problem.

**Comment by adamfarley** [comment]
Thanks Stewart. Rerunning.

**Comment by adamfarley** [comment]
Grinder tells us it all works now. Good job Stewart. :)

Closing.
